---
title: "ReadMe for Model Based Assessment of Weight Training"
author: B.A. McDougall\footnote{NSCI Consulting, bamcdougall@nsci-consulting.com}
date: "Wednesday, July 22, 2015"
output: html_document
---

## Abstract

This GitHub Repository contains a project for Predictive Machine Learning built within *R Studio*.  This Repository contains 32+ files.  The following files are primary files:

- **ReadMe.md** This file
- **ReadMe.txt** ReadMe.txt provides environment information for the build of this project
- **index.Rmd** index.Rmd is a file that generates content of the Predictive Machine Learning (PML) project.  The output is **index.html**.
- **CodeBook.md** CodeBook.Rmd contains definitions for a subset of variables of this PML Project
- **License** License is the GNU GENERAL PUBLIC LICENSE (version 2) 

## Additional Notes

- **index.html** is a front-end user-facing file comprising the gh-pages branch of this Repository.  The file is a html page for this *R Studio* project, which is [http://bamcdougall.github.io/Predictive_Machine_Learning_Human_Activity_Assessment](http://bamcdougall.github.io/Predictive_Machine_Learning_Human_Activity_Assessment).
